### ISSUE TITLE
Adding stack push, pop, IsEmpty, IsFull, peek operation code

### ISSUE THREAD

**Issue by kodeflap** [kodeflap/Algo_Guide#16]
- [ ] Create a package named stack 
- [ ] add stack kotlin class
- [ ] create functions for the operations pop, isEmpty, IsFull, Peek

**Comment by prPrashant786** [comment]
can i work on this?

**Comment by kodeflap** [comment]
> can i work on this?

Yes you can

**Comment by Iamkenji** [comment]
I'm new to github and coding in general , but I want to help. I have followed your instructions and created a package , class and the functions too except isFull (I can't get it to work). Can I still work with you on this?

**Comment by prPrashant786** [comment]
> 

I have created a pull request plzz check

**Comment by kodeflap** [comment]
@prPrashant786 I will be reviewing your PR request

**Comment by kodeflap** [comment]
@prPrashant786, @Iamkenji check out [To Do](https://github.com/kodeflap/Algo_Guide/blob/master/ToDo.md) for pending tasks in project for contribution also join [discord](https://discord.gg/8zdFPzQh) for additional discussion and doubts☺

**Comment by kodeflap** [comment]
> @prPrashant786 I will be reviewing your PR request

There is a review for your PR. To avoid merge conflicts can you update your project and add Code in Stack.kt and make another PR😇

**Comment by prPrashant786** [comment]
Hello sir/Mam my pull request is merge but it is showing not accepted in My Hactoberfest Id

**Comment by kodeflap** [comment]
@prPrashant786 Did you check your mail. Also your pull request will also be reviewed by hacktoberfest team so untill your Hacktoberfest profile will show a waiting message will you recheck your mail and also hacktoberfest profile
