### ISSUE TITLE
Implement Dijkstra's Algorithm

### ISSUE THREAD

**Issue by kodeflap** [kodeflap/Algo_Guide#17]
- [ ] create a package called dijkstra_algorithm
- [ ] Implement dijkstra's algorithm

**Comment by shashankdaima** [comment]
i want to do this. please assign this to me..

**Comment by kodeflap** [comment]
ok you can work on this issue👍

**Comment by anirudh0806** [comment]
I would like to work on this. Could you make me an assignee?

**Comment by shashankdaima** [comment]
@anirudh0806 I am working on this. but if you get assigned. than hit me a message on my telegram(you will get my telegram link from my profile `README.md`)

**Comment by kodeflap** [comment]
@anirudh0806, @shashankdaima Check out the [ToDo.md](https://github.com/kodeflap/Algo_Guide/blob/master/ToDo.md) and also join discord(https://discord.com/invite/8zdFPzQh) to get further updation and discussion for the project
