### ISSUE TITLE
Implement Queue Concept

### ISSUE THREAD

**Issue by kodeflap** [kodeflap/Algo_Guide#18]
Should implement different queue type concept in kotlin
This task should implement by creating queue package then seperate sub package for each type of queue.
Then implement each kotlin class for each

- [ ] Queue
- [ ] circular queue
- [ ] priority queue
- [ ] Deque

It's operations common for all type of queue

- [ ] Enqueue
- [ ] dequeue
- [ ] isEmpty
- [ ] isFull
- [ ] Peek

**Comment by ramyashreeshetty** [comment]
can i work on this?

**Comment by kodeflap** [comment]
yes, you can work on the issue

**Comment by ramyashreeshetty** [comment]
hey, actually i needed to confirm few things!
over here 
![image](https://user-images.githubusercontent.com/43513353/193511871-8e7b08ef-b275-49c9-a9a1-e1da316258fd.png)

1. as y'll have created Data_structures.linked_lists, I have to create Data_structures.queues?
2. under that i'll be creating queue, circular q, priority q and deque.

- correct me if i'm wrong

**Comment by kodeflap** [comment]
Create package called queue in algorithm and in there create sub packages

**Comment by ramyashreeshetty** [comment]
yes got it

**Comment by ramyashreeshetty** [comment]
for now i m completing the tasks, I havent commited anything so that wont be a problem. Do let me know when you are done wth formatting the project

**Comment by ramyashreeshetty** [comment]
@kodeflap hey i'm done with the tasks so can i create a pr?

**Comment by kodeflap** [comment]
> @kodeflap hey i'm done with the tasks so can i create a pr?

Yes, you can I will merge it

**Comment by ramyashreeshetty** [comment]
okay

**Comment by ramyashreeshetty** [comment]
hey could you assign this issue 😅
