### ISSUE TITLE
Implementing tree related algorithms

### ISSUE THREAD

**Issue by kodeflap** [kodeflap/Algo_Guide#28]
https://github.com/kodeflap/Algo_Guide/blob/master/ToDo.md

- [x] Check out the link and add algorithms in corresponding packages in the project

**Comment by AayushiSingh005** [comment]
Plz Assign it to me.

**Comment by kodeflap** [comment]
ok I will assign to you

**Comment by AayushiSingh005** [comment]
in which file do i have to write algorithm

**Comment by kodeflap** [comment]
I have already created packages named tree where you can add corresponding algorithm

![image](https://user-images.githubusercontent.com/86681482/194129726-360d41cc-e8bc-47e4-bdcd-b010f1521653.png)

**Comment by aritra-tech** [comment]
Can I also work on this issue @kodeflap

**Comment by kodeflap** [comment]
You can work on it
