### ISSUE TITLE
Add Array Programs

### ISSUE THREAD

**Issue by aritra-tech** [kodeflap/Algo_Guide#44]
Want to add basic operations of arrays such as:
- Deletion of elements  in the array
- Insertion of elements in the array
- Multidimensional Array
- Reverse an Array

Any other suggestions on what should I add except those operations @kodeflap?

**Comment by kodeflap** [comment]
> Want to add basic operations of arrays such as:
> 
> * Deletion of elements  in the array
> * Insertion of elements in the array
> * Multidimensional Array
> * Reverse an Array
> 
> Any other suggestions on what should I add except those operations @kodeflap?

You can also add search, update, and traversal sample programs

**Comment by aritra-tech** [comment]
> @aritra-tech You can also add search, update, and traversal sample programs

Ok sure
