### ISSUE TITLE
Deleting additional viewmodel in each sort package

### ISSUE THREAD

**Issue by kodeflap** [kodeflap/Algo_Guide#5]
Delete view model in

- [x]  Bubble sort package
- [x]  Merge sort package
- [x]  Quick sort package
- [x]  Selection sort package

**Comment by Fazil29** [comment]
I want to work on it.

**Comment by kodeflap** [comment]
Yes, you can work on it.
Just fork and create a new branch for the issue

**Comment by kodeflap** [comment]
This issue is closed
