### ISSUE TITLE
[Documentation] links to tutorials

### ISSUE THREAD

**Issue by kodeflap** [kodeflap/Algo_Guide#6]
This document should contain useful and best Ds and algorithm resources

- [ ] YouTube links
- [ ] Tutorial links
- [ ] best time complexity and space complexity links

To refer for other other developers

**Comment by Montekkundan** [comment]
Please assign it to me! Thanks 😄

**Comment by Jay179-sudo** [comment]
Hi! Just so we're clear, is the task to create a new "Resources.md" file in the root directory and put in all our links to the resources there? And by resources, I mean general DS & Algo resources, not specific to Kotlin as such? Thank you for clearing it up!

**Comment by kodeflap** [comment]
The main idea of this task is to provide with useful resources to understand the concepts🤓 about ds and algo and to use it for implementing it in Kotlin☺
