### ISSUE TITLE
Adding different search algorithm

### ISSUE THREAD

**Issue by kodeflap** [kodeflap/Algo_Guide#8]
[Check out it task](https://github.com/kodeflap/Algo_Guide/milestone/7) 
You have to implement the search algorithms in Kotlin.

- [x] First add search package
- [x] add sub search package
- [x] add search algorithm in respective package

**Comment by ken1000minus7** [comment]
I would like to work on this issue ✌️

**Comment by Fazil29** [comment]
Do we have to write binary search as well as linear search?

**Comment by kodeflap** [comment]
Hello check out the [milestone for this issue](https://github.com/kodeflap/Algo_Guide/milestone/7)

**Comment by ken1000minus7** [comment]
@kodeflap For dfs and bfs, should the input be an adjacency list?

**Comment by kodeflap** [comment]
yes

**Comment by kodeflap** [comment]
More than adding commenting use KDoc commenting method so that it will be easy to generate the documentation of code.

**Comment by ken1000minus7** [comment]
@kodeflap Ok will take care of that 😇

**Comment by ken1000minus7** [comment]
@kodeflap Just wanted to confirm, what should the dfs return? Should it return a boolean indicating whether a target element is found or should it return an array representing the depth first traversal?

**Comment by kodeflap** [comment]
It should return boolean indicating the value

**Comment by Fazil29** [comment]
Are there any more searches left to add?

**Comment by kodeflap** [comment]
I think it's almost over for search. You can work on other dsa concepts like array, stack, queue, tree etc. Algorithm. You just needed to raise a new issue about specific topic you are working😃

**Comment by shashankdaima** [comment]
Can I contribute to this issue?

**Comment by kodeflap** [comment]
> Can I contribute to this issue?

This issue is almost done 😅. But you can work on other DSA concepts just open a issue🙂
