### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by CS50X-RGB** [kodeflap/Algo_Guide#9]
I would like to add proper comments and output to explain the code properly 
@kodeflap can I get this issue 😅

**Comment by kodeflap** [comment]
Yes, the code is initial stage so you can add proper commenting in it using KDoc 🤓. For output It should be added to view model that is currently in progress🚧

**Comment by CS50X-RGB** [comment]
> Yes, the code is initial stage so you can add proper commenting in it using KDoc 🤓. For output It should be added to view model that is currently in progress🚧 

What's KDoc?? And how to acess & use that 😅

**Comment by kodeflap** [comment]
> > Yes, the code is initial stage so you can add proper commenting in it using KDoc 🤓. For output It should be added to view model that is currently in progress🚧
> 
> What's KDoc?? And how to acess & use that 😅
>
> It is a proper commenting language used in Kotlin to generate code documentation in HTML, md or javadoc

[Documentation in Kotlin using dokka and html](https://medium.com/@KodeFlap/document-kotlin-code-using-dokka-and-kdoc-part-1-139b472e966b)

**Comment by kodeflap** [comment]
To implement in here you just need to go to that class and type /** and press enter that's all

**Comment by CS50X-RGB** [comment]
> To implement in here you just need to go to that class and type  /** and press enter that's all 😃
> 
> If you still find it difficult you can also ask for help or just add proper comment you know 😇

Sure thanks for the help 😁

**Comment by CS50X-RGB** [comment]
@kodeflap mam i need some of help mam i dont know kotlin but i am familiar with java and dsa mam the code in bubble sort can improved can i change the code too!??

**Comment by CS50X-RGB** [comment]
And i have some doubts where can i contact u ??

**Comment by kodeflap** [comment]
> If you want to improve the code you can do it😃

**Comment by kodeflap** [comment]
> And i have some doubts where can i contact u ??

You can join the discord if you have any doubt

**Comment by CS50X-RGB** [comment]
Hi u didn't closed the issue @kodeflap
